#!/bin/bash

name=$(./jq.exe -r '.name' data.json)
height=$(./jq.exe -r '.height' data.json)
weight=$(./jq.exe -r '.weight' data.json)
type=$(./jq.exe -r '.types[0].type.name' data.json)

if [[ -z "$name" || -z "$height" || -z "$weight" || -z "$type" ]]; then
  echo "Error: Could not extract all required data."
  exit 1
fi

formatted_height=$(awk "BEGIN {printf \"%.1f\", $height / 10}")
formatted_weight=$(awk "BEGIN {printf \"%d\", $weight / 10}")

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall." | \
sed -E 's/^([a-z])/\U\1/; s/(of type )([a-z])/\1\u\2/'